### PR TITLE
Add syntax highlighting to readme

### PR DESCRIPTION
**Pull request by ZevEisenberg**
You might want to view this PR [with whitespace changes hidden](https://github.com/bup/bup/pull/48/files?utf8=✓&diff=unified&w=1), since it makes it easier to read, but also look at the rendered Markdown preview.

### CODE REVIEW

**Comment by rlbdv** [comment]
Thanks for the help. In accordance with HACKING I've redirected this pull request to the list for discussion: https://groups.google.com/d/msg/bup-list/3U6aMfr_ZBU/VoilY63FAgAJ

If you're comfortable with a Signed-off-by, we'd love to consider your work for inclusion -- you could either update this patch to include a psuedo-header like the one in this commit message: https://github.com/bup/bup/commit/2d31b9d8defbacb19934bcfc5388e1d9815e67d2, or reply to the bup-list post indicated above.

**Comment by rlbdv** [comment]
Overall, looks good.

**Comment by ZevEisenberg** [comment]
Rebased with a sign-off

**Comment by ZevEisenberg** [comment]
It occurred to me that I actually wasn’t sure if you meant I needed to add a sign-off as myself, or as you, @rlbdv, so just let me know.

**Comment by rlbdv** [comment]
Zev Eisenberg <notifications@github.com> writes:

> It occurred to me that I actually wasn’t sure if you meant I needed to
> add a sign-off as myself, or as you, @rlbdv, so just let me know.

Ahh right -- as you.  You added exactly the right thing (see
SIGNED-OFF-BY in the tree).

Thanks again for the help, and it should be included it in my next
update.
-- 
Rob Browning
rlb @defaultvalue.org and @debian.org
GPG as of 2011-07-10 E6A9 DA3C C9FD 1FF8 C676 D2C4 C0F0 39E9 ED1B 597A
GPG as of 2002-11-03 14DD 432F AE39 534D B592 F9A0 25C8 D377 8C7E 73A4

**Comment by rlbdv** [comment]
Thanks much -- included in master as cb23ba7502f3d9b8c266d3e214b34ae1fc3372ba

**Pull request closed without merging**
